<a href="https://colab.research.google.com/github/shravaniphalke805/Python-Libraries/blob/main/assignment13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# a) Create a 1D array
array1 = np.array([10, 20, 30, 40, 50])

# b) Create a 3x3 2D array
array2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Print 1D array details
print("1D Array:")
print(array1)
print("Shape:", array1.shape)
print("Data Type:", array1.dtype)

print()

# Print 2D array details
print("2D Array:")
print(array2)
print("Shape:", array2.shape)
print("Data Type:", array2.dtype)

1D Array:
[10 20 30 40 50]
Shape: (5,)
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64


In [ ]:
import numpy as np

# a) 1D array of 8 zeros
array1 = np.zeros(8)

# b) 2D array of shape (4, 4) filled with ones
array2 = np.ones((4, 4))

# c) 3x3 matrix of zeros
array3 = np.zeros((3, 3))

# Print all arrays with proper labels
print("a) 1D Array of 8 Zeros:")
print(array1)

print("\nb) 4x4 Array of Ones:")
print(array2)

print("\nc) 3x3 Matrix of Zeros:")
print(array3)

a) 1D Array of 8 Zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

b) 4x4 Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

c) 3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

# a) Numbers from 0 to 20 (step 1)
array1 = np.arange(0, 21, 1)

# b) Even numbers from 10 to 50
array2 = np.arange(10, 51, 2)

# c) Numbers from 5 to 100 with step of 5
array3 = np.arange(5, 101, 5)

# Print the arrays
print("a) Numbers from 0 to 20:")
print(array1)

print("\nb) Even numbers from 10 to 50:")
print(array2)

print("\nc) Numbers from 5 to 100 with step of 5:")
print(array3)

a) Numbers from 0 to 20:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

b) Even numbers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

c) Numbers from 5 to 100 with step of 5:
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [ ]:
import numpy as np

# a) 10 equally spaced numbers between 0 and 5
array1 = np.linspace(0, 5, 10)

# b) 15 equally spaced numbers between -10 and 10
array2 = np.linspace(-10, 10, 15)

# Print the arrays and their lengths
print("a) 10 equally spaced numbers between 0 and 5:")
print(array1)
print("Length:", len(array1))

print("\nb) 15 equally spaced numbers between -10 and 10:")
print(array2)
print("Length:", len(array2))


a) 10 equally spaced numbers between 0 and 5:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10

b) 15 equally spaced numbers between -10 and 10:
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


In [ ]:
import numpy as np

# a) 1D array of 10 random numbers between 0 and 1
array1 = np.random.rand(10)

# b) 3x3 matrix of random numbers from standard normal distribution
array2 = np.random.randn(3, 3)

# c) 4x5 array of random integers between 10 and 50
array3 = np.random.randint(10, 51, size=(4, 5))

# Print all arrays with proper headings
print("a) 1D Array of 10 Random Numbers (0 to 1):")
print(array1)

print("\nb) 3x3 Matrix of Random Numbers (Standard Normal Distribution):")
print(array2)

print("\nc) 4x5 Array of Random Integers (10 to 50):")
print(array3)

a) 1D Array of 10 Random Numbers (0 to 1):
[0.72872084 0.10361485 0.74343758 0.42118855 0.37813077 0.84649904
 0.37998578 0.59720326 0.37492688 0.32436372]

b) 3x3 Matrix of Random Numbers (Standard Normal Distribution):
[[ 2.16947497  0.27199276  0.47086948]
 [ 0.81377129 -0.53701302  0.57903275]
 [ 2.69985484  0.91292593 -0.53398172]]

c) 4x5 Array of Random Integers (10 to 50):
[[46 10 41 25 41]
 [31 31 45 44 18]
 [35 14 13 14 30]
 [10 24 27 21 20]]


In [ ]:
import numpy as np

# Create two vectors
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

# Perform operations
addition = v1 + v2
subtraction = v1 - v2
multiplication = v1 * v2
dot_product = np.dot(v1, v2)

# Print the results
print("Vector 1:", v1)
print("Vector 2:", v2)

print("\nAddition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nDot Product:")
print(dot_product)

Vector 1: [2 4 6 8]
Vector 2: [1 3 5 7]

Addition:
[ 3  7 11 15]

Subtraction:
[1 1 1 1]

Element-wise Multiplication:
[ 2 12 30 56]

Dot Product:
100


In [ ]:
import numpy as np

# Create two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Matrix Addition
addition = A + B

# Matrix Multiplication
matrix_multiplication = A @ B
# (You can also use: np.dot(A, B))

# Element-wise Multiplication
elementwise_multiplication = A * B

# Print the results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Addition (A + B):")
print(addition)

print("\nMatrix Multiplication (A @ B):")
print(matrix_multiplication)

print("\nElement-wise Multiplication (A * B):")
print(elementwise_multiplication)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication (A @ B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
import numpy as np

# Create a 4x4 matrix of random integers between 1 and 100
matrix = np.random.randint(1, 101, size=(4, 4))

# Print the matrix
print("4x4 Random Integer Matrix:")
print(matrix)

# Print array properties
print("\nShape:", matrix.shape)
print("Dimension (ndim):", matrix.ndim)
print("Total Number of Elements (size):", matrix.size)
print("Data Type:", matrix.dtype)
print("Minimum Value:", matrix.min())
print("Maximum Value:", matrix.max())

4x4 Random Integer Matrix:
[[60 84 50 53]
 [67 89  3 33]
 [69 31 60 51]
 [49 93 69 94]]

Shape: (4, 4)
Dimension (ndim): 2
Total Number of Elements (size): 16
Data Type: int64
Minimum Value: 3
Maximum Value: 94


In [ ]:
import numpy as np

# Generate a 1D array of 20 random integers between 1 and 50
arr = np.random.randint(1, 51, 20)

# Reshape into a 4x5 matrix
matrix = arr.reshape(4, 5)

# Display the matrix
print("Matrix:")
print(matrix)

# Sum, Mean, and Standard Deviation
print("\nSum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

# Maximum value in each row
print("\nMaximum value in each row:")
print(np.max(matrix, axis=1))

Matrix:
[[35 29 14 25 24]
 [37  6 19 34 15]
 [31 23 39  7  7]
 [27 30  1 24 16]]

Sum: 443
Mean: 22.15
Standard Deviation: 10.882439983753642

Maximum value in each row:
[35 37 39 30]


In [ ]:
import numpy as np
try:
    # Ask the user how many numbers to generate
    n = int(input("Enter the number of random numbers to generate: "))
    # Check for valid input
    if n <= 0:
        raise ValueError("Number must be greater than 0.")
    # Generate random numbers between 10 and 100
    arr = np.random.randint(10, 101, n)

    # Print the array
    print("\nGenerated Array:")
    print(arr)
    # Print statistics
    print("\nStatistics:")
    print("Mean:", np.mean(arr))
    print("Median:", np.median(arr))
    print("Standard Deviation:", np.std(arr))
    print("Minimum:", np.min(arr))
    print("Maximum:", np.max(arr))
    # Reshape into a 2D array if possible
    rows = int(np.sqrt(n))
    while rows > 1:
        if n % rows == 0:
            cols = n // rows
            matrix = arr.reshape(rows, cols)
            print("\nReshaped 2D Array:")
            print(matrix)
            print("\nRow-wise Sum:")
            print(np.sum(matrix, axis=1))
            break
        rows -= 1
    else:
        print("\nCannot reshape into a proper 2D array.")
except ValueError as e:
    print("Error:", e)

except Exception as e:
    print("An unexpected error occurred:", e)

Enter the number of random numbers to generate: 50

Generated Array:
[30 93 18 10 49 89 76 85 42 70 67 65 89 49 24 69 72 33 45 20 76 51 17 52
 10 76 46 28 24 57 75 24 88 39 63 74 75 56 37 51 88 24 12 85 41 50 36 48
 90 45]

Statistics:
Mean: 52.66
Median: 50.5
Standard Deviation: 24.324974820130855
Minimum: 10
Maximum: 93

Reshaped 2D Array:
[[30 93 18 10 49 89 76 85 42 70]
 [67 65 89 49 24 69 72 33 45 20]
 [76 51 17 52 10 76 46 28 24 57]
 [75 24 88 39 63 74 75 56 37 51]
 [88 24 12 85 41 50 36 48 90 45]]

Row-wise Sum:
[562 533 437 582 519]
