<a href="https://colab.research.google.com/github/shravaniphalke805/Python-Libraries/blob/main/assignment14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q1.Array Properties
import numpy as np

# Create a 2D array of shape (5, 6) with random integers between 10 and 100
arr = np.random.randint(10, 101, size=(5, 6))

# Print the array
print("Array:\n", arr)

# Print properties
print("Shape of the array:", arr.shape)
print("Total number of elements (size):", arr.size)
print("Data type (dtype):", arr.dtype)

Array:
 [[41 76 90 91 52 30]
 [28 38 51 44 77 71]
 [52 27 50 72 53 81]
 [41 12 91 82 17 50]
 [57 46 74 64 90 40]]
Shape of the array: (5, 6)
Total number of elements (size): 30
Data type (dtype): int64


In [ ]:
# Q2.Statistical Methods - Basic
import numpy as np

# Generate a 1D array of 20 random integers between 1 and 50
arr = np.random.randint(1, 51, 20)

# Print the array
print("Array:", arr)

# Statistical methods
print("Minimum value:", arr.min())
print("Index of minimum value (argmin):", arr.argmin())

print("Maximum value:", arr.max())
print("Index of maximum value (argmax):", arr.argmax())

print("Sum of all elements:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())

Array: [44 39 11 16 40 35 21 50 37  5 36  5  2 11 15 31 19 42 19  3]
Minimum value: 2
Index of minimum value (argmin): 12
Maximum value: 50
Index of maximum value (argmax): 7
Sum of all elements: 481
Mean: 24.05
Standard Deviation: 15.087991914101757


In [ ]:
# Q3. Statistical Methods on 2D Array

import numpy as np

# Create a 4x5 matrix of random integers between 20 and 80
matrix = np.random.randint(20, 81, size=(4, 5))

# Print the matrix
print("Matrix:\n", matrix)

# Statistical methods for the entire matrix
print("\nMinimum value:", matrix.min())
print("Maximum value:", matrix.max())
print("Sum of all elements:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Deviation:", matrix.std())

# Sum of each row and each column
print("\nSum of each row:", matrix.sum(axis=1))
print("Sum of each column:", matrix.sum(axis=0))

Matrix:
 [[74 62 27 42 28]
 [74 67 40 53 26]
 [75 44 76 69 54]
 [20 23 39 56 26]]

Minimum value: 20
Maximum value: 76
Sum of all elements: 975
Mean: 48.75
Standard Deviation: 19.224658644563757

Sum of each row: [233 260 318 164]
Sum of each column: [243 196 182 220 134]


In [ ]:
# Q4. Reshape

import numpy as np

# Create a 1D array containing numbers from 1 to 24
arr = np.arange(1, 25)

print("Original Array:")
print(arr)
print("Shape:", arr.shape)

# Reshape into (4, 6)
arr1 = arr.reshape(4, 6)
print("\nReshaped Array (4, 6):")
print(arr1)
print("Shape:", arr1.shape)

# Reshape into (3, 8)
arr2 = arr.reshape(3, 8)
print("\nReshaped Array (3, 8):")
print(arr2)
print("Shape:", arr2.shape)

# Reshape into (2, 3, 4)
arr3 = arr.reshape(2, 3, 4)
print("\nReshaped Array (2, 3, 4):")
print(arr3)
print("Shape:", arr3.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)

Reshaped Array (4, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Reshaped Array (3, 8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Reshaped Array (2, 3, 4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [ ]:
# Q5. NumPy Indexing - 1D & 2D

import numpy as np

# Create the array
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("Original Array:")
print(arr)

# Extract first row
print("\nFirst Row:")
print(arr[0])

# Extract last column
print("\nLast Column:")
print(arr[:, -1])

# Extract center 2x2 submatrix
print("\nCenter 2x2 Submatrix:")
print(arr[1:3, 1:3])

# Extract all even numbers using boolean indexing
print("\nEven Numbers:")
print(arr[arr % 2 == 0])

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row:
[10 20 30 40]

Last Column:
[ 40  80 120]

Center 2x2 Submatrix:
[[ 60  70]
 [100 110]]

Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [ ]:
# Q6. Advanced Indexing

import numpy as np

# Create a 5x5 matrix of random integers between 1 and 100
arr = np.random.randint(1, 101, size=(5, 5))

# Print the original array
print("Original Array:")
print(arr)

# Print the diagonal elements
print("\nDiagonal Elements:")
print(np.diag(arr))

# Print elements greater than 50
print("\nElements Greater Than 50:")
print(arr[arr > 50])

# Replace all elements less than 30 with 0
arr[arr < 30] = 0

# Print the modified array
print("\nModified Array (Elements < 30 replaced with 0):")
print(arr)

Original Array:
[[58 73 42 33 79]
 [91 94 15 55 91]
 [75 97 23 75 13]
 [11 57 51 30 34]
 [72 83 95 22 32]]

Diagonal Elements:
[58 94 23 30 32]

Elements Greater Than 50:
[58 73 79 91 94 55 91 75 97 75 57 51 72 83 95]

Modified Array (Elements < 30 replaced with 0):
[[58 73 42 33 79]
 [91 94  0 55 91]
 [75 97  0 75  0]
 [ 0 57 51 30 34]
 [72 83 95  0 32]]


In [ ]:
# Q7. Arithmetic Operations

import numpy as np

# Create the arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array a:", a)
print("Array b:", b)

# Addition
print("\nAddition:")
print(a + b)

# Subtraction
print("\nSubtraction:")
print(a - b)

# Multiplication
print("\nMultiplication:")
print(a * b)

# Division
print("\nDivision:")
print(a / b)

# Element-wise Power
print("\nElement-wise Power (a ** b):")
print(a ** b)

# Modulo Operation
print("\nModulo (a % b):")
print(a % b)

Array a: [10 20 30 40]
Array b: [1 2 3 4]

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]

Element-wise Power (a ** b):
[     10     400   27000 2560000]

Modulo (a % b):
[0 0 0 0]


In [ ]:
# Q8. Matrix Multiplication

import numpy as np

# Create the matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Element-wise multiplication
# Multiplies corresponding elements of A and B.
elementwise = A * B

print("\nElement-wise Multiplication (A * B):")
print(elementwise)

# Matrix multiplication
# Multiplies rows of A with columns of B.
matrix_mult = A @ B
# You can also use: matrix_mult = np.dot(A, B)

print("\nMatrix Multiplication (A @ B):")
print(matrix_mult)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication (A @ B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
# Q9.Combined - Properties + Operations + Indexing
import numpy as np

# Generate a 6x6 matrix of random numbers
mat = np.random.randn(6, 6)

# Print shape, size, dtype
print("Matrix:\n", mat)
print("\nShape:", mat.shape)
print("Size:", mat.size)
print("Dtype:", mat.dtype)

# Index of max and min value
max_index = np.unravel_index(np.argmax(mat), mat.shape)
min_index = np.unravel_index(np.argmin(mat), mat.shape)

print("\nIndex of maximum value:", max_index)
print("Index of minimum value:", min_index)

# Extract top-left 3x3 submatrix
submatrix = mat[:3, :3]
print("\nTop-left 3x3 submatrix:\n", submatrix)

# Replace all negative numbers with absolute values
mat_abs = np.abs(mat)
print("\nMatrix after replacing negatives with absolute values:\n", mat_abs)

# Mean of modified matrix
mean_value = np.mean(mat_abs)
print("\nMean of modified matrix:", mean_value)

Matrix:
 [[ 2.24199042e+00 -1.98332556e+00 -1.79387501e+00  6.31954115e-01
   1.26649993e+00  1.03552604e+00]
 [ 1.32503691e+00 -5.88731355e-01  8.80994347e-02  6.73393168e-01
  -1.61014931e-01  4.01025723e-02]
 [ 8.22899111e-01  6.43695829e-01 -5.00246003e-02  1.00484017e+00
  -7.81300731e-01 -1.20637588e+00]
 [ 8.89127811e-01 -8.64317935e-02 -7.51085294e-01 -1.30091749e-03
   1.96581905e-01 -8.66509726e-01]
 [ 1.18985787e+00  2.18194600e-01  1.89963671e+00 -2.85879145e-01
   1.16026468e+00 -1.31700514e+00]
 [-3.44002395e-01  1.46807957e+00  1.23810547e+00 -6.53101871e-01
  -9.79981451e-01 -2.37779509e-01]]

Shape: (6, 6)
Size: 36
Dtype: float64

Index of maximum value: (np.int64(0), np.int64(0))
Index of minimum value: (np.int64(0), np.int64(1))

Top-left 3x3 submatrix:
 [[ 2.24199042 -1.98332556 -1.79387501]
 [ 1.32503691 -0.58873136  0.08809943]
 [ 0.82289911  0.64369583 -0.0500246 ]]

Matrix after replacing negatives with absolute values:
 [[2.24199042e+00 1.98332556e+00 1.7938750

In [ ]:
# Q10.Mini Project - Student Performance Analysis

import numpy as np

# Step 1: Generate random marks
marks = np.random.randint(30, 101, size=(10, 5))
print("Student Marks (10x5):\n", marks)

# Step 2: Total and average marks per student
total_marks = np.sum(marks, axis=1)
average_marks = np.mean(marks, axis=1)
print("\nTotal Marks per Student:\n", total_marks)
print("\nAverage Marks per Student:\n", average_marks)

# Step 3: Find top and lowest scoring students
top_student = np.argmax(total_marks)
low_student = np.argmin(total_marks)
print("\nTop Scoring Student Index:", top_student)
print("Lowest Scoring Student Index:", low_student)

# Step 4: Class statistics
class_mean = np.mean(marks)
class_std = np.std(marks)
print("\nClass Mean Marks:", class_mean)
print("Class Standard Deviation:", class_std)

# Step 5: Reshaping (flatten and restore example)
flattened = marks.reshape(-1)      # convert to 1D
reshaped_back = flattened.reshape(10, 5)
print("\nFlattened array shape:", flattened.shape)
print("Reshaped back array shape:", reshaped_back.shape)

# Step 6: Extract top 3 students
top_3_indices = np.argsort(total_marks)[-3:][::-1]
top_3_students = marks[top_3_indices]
print("\nTop 3 Students (Marks):\n", top_3_students)
print("\nTop 3 Student Indices:", top_3_indices)

Student Marks (10x5):
 [[34 37 78 95 44]
 [51 40 79 70 64]
 [76 42 97 73 48]
 [75 73 81 56 57]
 [88 30 71 36 78]
 [37 41 60 42 83]
 [89 79 81 42 41]
 [49 90 97 44 50]
 [57 93 72 54 58]
 [85 59 95 86 38]]

Total Marks per Student:
 [288 304 336 342 303 263 332 330 334 363]

Average Marks per Student:
 [57.6 60.8 67.2 68.4 60.6 52.6 66.4 66.  66.8 72.6]

Top Scoring Student Index: 9
Lowest Scoring Student Index: 5

Class Mean Marks: 63.9
Class Standard Deviation: 20.072119967756272

Flattened array shape: (50,)
Reshaped back array shape: (10, 5)

Top 3 Students (Marks):
 [[85 59 95 86 38]
 [75 73 81 56 57]
 [76 42 97 73 48]]

Top 3 Student Indices: [9 3 2]
